### ISSUE TITLE
闫晋梁

### ISSUE THREAD

**Issue by mythologicalwarrior** [GayStudio/dutylog#23]
# Android Lab 值日登记
姓名：  闫晋梁
A 周希望选择的时间（填两个时间，精确到课程）：   周六晚自习，
B 周希望选择的时间（填两个时间，精确到课程）：     周五晚自习，周六晚自习
是否因为过于繁忙，只能接受一周值日一次：都可以

## 请在下方粘贴您的课表
![5p_2g2h6 x3gwh jj 1x v](https://user-images.githubusercontent.com/44321177/47262273-f1f28600-d516-11e8-8b91-5f138485ecfe.png)

**粘贴注意事项**：   
* 请粘贴高清截图
* 请将课标补充完整后再截图，包括社团活动和学生会事务

**Comment by kenvix** [comment]
全部无法满足，请重选
