### ISSUE TITLE
孙雨轩

### ISSUE THREAD

**Issue by artimisgood** [GayStudio/dutylog#25]
# Android Lab 值日登记
姓名： 孙雨轩 
A 周希望选择的时间（填两个时间，精确到课程）： 周一周二下午第一节  
B 周希望选择的时间（填两个时间，精确到课程）：   周六下午两节
是否因为过于繁忙，只能接受一周值日一次：否   

## 请在下方粘贴您的课表
![screenshot_2018-10-21-11-28-49-27](https://user-images.githubusercontent.com/44323318/47262833-5583b000-d525-11e8-9f8c-be74f5495b50.png)

**粘贴注意事项**：   
 * 请粘贴高清截图
 * 请将课表补充完整后再截图，包括社团活动和学生会事务
 * 粘贴后显示为 "Uploading" 表示正在上传，应稍等一会。   
   待显示为类似 \[A]\(B) 的格式后方可提交
 * 精确到课程：即说明要在申请在哪节课的时间值班，例如 周六上午第二节
 * 请同时在 ISSUE 标题处写上自己的姓名

**Comment by kenvix** [comment]
有一项无法满足，请再选一节课
