### ISSUE TITLE
张馨月

### ISSUE THREAD

**Issue by lemonis** [GayStudio/dutylog#27]
# Android Lab 值日登记
姓名：  张馨月
A 周希望选择的时间（填两个时间，精确到课程）：   周四下午第一节课和周五下午第二节课
B 周希望选择的时间（填两个时间，精确到课程）：   周四下午第一节课和周五下午第二节课
是否因为过于繁忙，只能接受一周值日一次：否   

## 请在下方粘贴您的课表

**粘贴注意事项**：   
 * 请粘贴高清截图
 * 请将课表补充完整后再截图，包括社团活动和学生会事务
 * 粘贴后显示为 "Uploading" 表示正在上传，应稍等一会。   
   待显示为类似 \[A]\(B) 的格式后方可提交
 * 精确到课程：即说明要在申请在哪节课的时间值班，例如 周六上午第二节
 * 请同时在 ISSUE 标题处写上自己的姓名       

![img](http://wx4.sinaimg.cn/mw690/0060lm7Tly1fwfpsdby7vj30f00qo0u9.jpg)

**Comment by kenvix** [comment]
有一项无法满足，请再选一节课
