### ISSUE TITLE
张世杰

### ISSUE THREAD

**Issue by ZSJ6** [GayStudio/dutylog#6]
# Android Lab 值日登记
姓名：  张世杰
A 周希望选择的时间（填两个时间）：   周三上午第二节、周三下午晚上
B 周希望选择的时间（填两个时间）：   周二下午一二节、周一上午第二节
是否因为过于繁忙，只能接受一周值日一次：否   

## 请在下方粘贴您的课表
![Uploading Screenshot_2018-10-20-20-50-11-247_com.xtuone.and.png…]()

**Comment by kenvix** [comment]
课表上传失败，请重新上传

**Comment by ZSJ6** [comment]
![screenshot_2018-10-20-20-50-11-247_com xtuone and](https://user-images.githubusercontent.com/44318175/47265031-3ea88200-d554-11e8-81e0-68a2ba69d974.png)
